name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/astronuts'
  ARTIFACT: 'webHelpASTRONUTS2-all.zip'
  DOCKER_VERSION: '241.15989'
  ALGOLIA_ARTIFACT: 'algolia-indexes-ASTRONUTS.zip'
  ALGOLIA_APP_NAME: 'QNSY1C3U5R'
  ALGOLIA_INDEX_NAME: 'prod_ASTRONUTSDOCS'
  ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY }}'
  CONFIG_JSON_PRODUCT: 'ASTRONUTS'
  CONFIG_JSON_VERSION: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build documentation
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
            artifacts/report.json
          retention-days: 7
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: docs
#          path: artifacts
#
#      - name: Test documentation
#        uses: JetBrains/writerside-checker-action@v1
#        with:
#          instance: ${{ env.INSTANCE }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Unzip artifact
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d docsite
      - uses: kefranabg/s3-sync-action@master
        name: Deploy and invalidate docs cache
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.ASTRONUTS_DOCS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './docsite'
          DEST_DIR: ''
          DISTRIBUTION_ID: ${{ secrets.ASTRONUTS_DOCS_CF_DISTRIBUTION }}
      - name: Invalidate website cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.ASTRONUTS_WEBSITE_CF_DISTRIBUTION }}
          PATHS: "/docs /docs/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  publish-indexes:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-3
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Unzip artifact
        run: |
          unzip -O UTF-8 -qq '${{ env.ALGOLIA_ARTIFACT }}' -d algolia-indexes
          env algolia-key='${{env.ALGOLIA_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name '${{env.ALGOLIA_APP_NAME}}' \
          --index-name '${{env.ALGOLIA_INDEX_NAME}}' \
          --product '${{env.CONFIG_JSON_PRODUCT}}' \
          --version '${{env.CONFIG_JSON_VERSION}}' \
          --index-directory algolia-indexes/ \
          2>&1 | tee algolia-update-index-log.txt